[project]
name = "dep-fc"
version = "0.0.1"
description = "Digital Earth Pacific Fractional Cover Unmixing"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dep-tools",
    "scikit-build",
    "setuptools",
    "typer",
    "typing-extensions",
    "dea-tools",
    #"scipy<0.15", #for linux systems only
]

[tool.uv.sources]
dep-tools = { git = "https://github.com/digitalearthpacific/dep-tools.git" }
